name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

#include <stdio.h>
main (){
int power(int m,int n);
for((i=getchar()),!=EOF)
printf("%d\n",power i);
return 0;
}
int power(int base,int n){
int i,p
p=1
p=p*base;
return p
}
